import type { EmployeeSectionId } from './employeeSections';

export type SeedEmployee = {
  serial: number;
  name: string;
  sectionId: EmployeeSectionId;
};

export const SEED_EMPLOYEES: SeedEmployee[] = [
  { serial: 1, name: 'মোঃ জাবেদ (ম্যানেজার)', sectionId: 'management' },
  { serial: 2, name: 'এস.এম. ইমরুল কায়েশ (দিপু)', sectionId: 'management' },
  { serial: 3, name: 'মোঃ আতিকুর রহমান', sectionId: 'management' },
  { serial: 4, name: 'মোঃ জিয়ো', sectionId: 'management' },
  { serial: 5, name: 'মোঃ আতিকুল রহমান', sectionId: 'management' },
  { serial: 6, name: 'মোঃ মিজান', sectionId: 'management' },
  { serial: 7, name: 'শোভন দত্ত', sectionId: 'computer_operator' },
  { serial: 8, name: 'মোঃ ফয়সাল কাদের', sectionId: 'audit' },
  { serial: 9, name: 'মোঃ আরিফ', sectionId: 'audit' },
  { serial: 10, name: 'মোঃ নজরুল ইসলাম', sectionId: 'cashier' },
  { serial: 11, name: 'মোঃ আলামগীর', sectionId: 'cashier' },
  { serial: 12, name: 'মোঃ আকতার', sectionId: 'cashier' },
  { serial: 13, name: 'মোঃ সোহাগ', sectionId: 'cashier' },
  { serial: 14, name: 'মোঃ মোর্শেদ মাস্টার', sectionId: 'marketing' },
  { serial: 15, name: 'মোঃ সুজন', sectionId: 'floor' },
  { serial: 16, name: 'মোঃ মোজাম্মেল', sectionId: 'floor' },
  { serial: 17, name: 'মোঃ আসিফ', sectionId: 'bill_ferani' },
  { serial: 18, name: 'মোঃ হাসনাইন', sectionId: 'bill_ferani' },
  { serial: 19, name: 'সাগর তাতি', sectionId: 'bill_ferani' },
  { serial: 20, name: 'মোঃ জাহেদ', sectionId: 'bill_ferani' },
  { serial: 21, name: 'মোঃ কবির', sectionId: 'bill_ferani' },
  { serial: 22, name: 'মোঃ নয়ন', sectionId: 'bill_ferani' },
  { serial: 23, name: 'মোঃ মুবিন', sectionId: 'bill_ferani' },
  { serial: 24, name: 'মোঃ আব্বাস', sectionId: 'bangla_barbi_stand' },
  { serial: 25, name: 'মোঃ জাবেদ', sectionId: 'bangla_barbi_stand' },
  { serial: 26, name: 'মোঃ আব্দুর রহমান', sectionId: 'bangla_barbi_stand' },
  { serial: 27, name: 'মোঃ মুকিতুর', sectionId: 'bangla_barbi_stand' },
  { serial: 28, name: 'মোঃ মিজান', sectionId: 'bangla_barbi_stand' },
  { serial: 29, name: 'মোঃ আল-আমিন', sectionId: 'bangla_barbi_stand' },
  { serial: 30, name: 'মোঃ রিয়াজ', sectionId: 'bangla_barbi_stand' },
  { serial: 31, name: 'মোঃ সোলেমান', sectionId: 'bangla_barbi_stand' },
  { serial: 32, name: 'মোঃ শাহিন', sectionId: 'bangla_barbi_stand' },
  { serial: 33, name: 'মোঃ শাহিন', sectionId: 'parota_stand' },
  { serial: 34, name: 'মোঃ বাবলু', sectionId: 'parota_stand' },
  { serial: 35, name: 'মোঃ মাসুদ', sectionId: 'parota_stand' },
  { serial: 36, name: 'মোঃ জাহেদ', sectionId: 'parota_stand' },
  { serial: 37, name: 'মোঃ স্বপন', sectionId: 'parota_stand' },
  { serial: 38, name: 'মোঃ মাসুদ', sectionId: 'jhal_stand' },
  { serial: 39, name: 'মোঃ ইমরান', sectionId: 'jhal_stand' },
  { serial: 40, name: 'মোঃ ইয়াছিন', sectionId: 'ruti_stand' },
  { serial: 41, name: 'মোঃ সজিব', sectionId: 'ruti_stand' },
  { serial: 42, name: 'মোঃ ইমন', sectionId: 'ruti_stand' },
  { serial: 43, name: 'মোঃ নয়ন', sectionId: 'haddi_stand' },
  { serial: 44, name: 'মোঃ মোর্শেদ', sectionId: 'haddi_stand' },
  { serial: 45, name: 'বিকাশ', sectionId: 'haddi_stand' },
  { serial: 46, name: 'মোঃ শাহজালাল', sectionId: 'grill_stand' },
  { serial: 47, name: 'মোঃ ফারুক', sectionId: 'grill_stand' },
  { serial: 48, name: 'মোঃ তানভীর', sectionId: 'grill_stand' },
  { serial: 49, name: 'মোঃ মামুন', sectionId: 'grill_stand' },
  { serial: 50, name: 'মোঃ মহিউল', sectionId: 'electrician' },
  { serial: 51, name: 'মোঃ জহির', sectionId: 'tea_stand' },
  { serial: 52, name: 'মোঃ রবিন', sectionId: 'tea_stand' },
  { serial: 53, name: 'মোঃ সজিব', sectionId: 'tea_stand' },
  { serial: 54, name: 'মোঃ রাশেদ', sectionId: 'plate_boy' },
  { serial: 55, name: 'অভয়', sectionId: 'plate_boy' },
  { serial: 56, name: 'রণজিত', sectionId: 'plate_boy' },
  { serial: 57, name: 'অকিত ঘোষ', sectionId: 'plate_boy' },
  { serial: 58, name: 'মোঃ রবিউল ইসলাম', sectionId: 'parcel_boy' },
  { serial: 59, name: 'মোঃ নজমুল', sectionId: 'parcel_boy' },
  { serial: 60, name: 'মোঃ রিপন', sectionId: 'parcel_boy' },
  { serial: 61, name: 'মোঃ সাবির', sectionId: 'parcel_boy' },
  { serial: 62, name: 'মোঃ শাহিন', sectionId: 'parcel_boy' },
  { serial: 63, name: 'মোঃ মিরাজ', sectionId: 'bangla_table_boy' },
  { serial: 64, name: 'মোঃ মোর্শেদ', sectionId: 'bangla_table_boy' },
  { serial: 65, name: 'মোঃ মনির হোসেন', sectionId: 'bangla_table_boy' },
  { serial: 66, name: 'মোঃ তানভিদ', sectionId: 'bangla_table_boy' },
  { serial: 67, name: 'মোঃ আরিফ', sectionId: 'bangla_table_boy' },
  { serial: 68, name: 'মোঃ রবিউল ইসলাম', sectionId: 'bangla_table_boy' },
  { serial: 69, name: 'মোঃ নুরু উদ্দীন', sectionId: 'bangla_table_boy' },
  { serial: 70, name: 'মোঃ সেলিম', sectionId: 'bangla_table_boy' },
  { serial: 71, name: 'মোঃ রাবি', sectionId: 'bangla_table_boy' },
  { serial: 72, name: 'মোঃ সাগর', sectionId: 'bangla_table_boy' },
  { serial: 73, name: 'মোঃ সজিব', sectionId: 'bangla_table_boy' },
  { serial: 74, name: 'মোঃ রাকিব', sectionId: 'bangla_table_boy' },
  { serial: 75, name: 'মোঃ জসিম', sectionId: 'bangla_glass_boy' },
  { serial: 76, name: 'মোঃ ইমাইল', sectionId: 'bangla_glass_boy' },
  { serial: 77, name: 'মোঃ রায়হান', sectionId: 'bangla_glass_boy' },
  { serial: 78, name: 'মোঃ তানভিদ', sectionId: 'bangla_glass_boy' },
  { serial: 79, name: 'মোঃ আল আমিন', sectionId: 'bangla_glass_boy' },
  { serial: 80, name: 'মোঃ ইব্রাহিম', sectionId: 'bangla_glass_boy' },
  { serial: 81, name: 'মোঃ জহির', sectionId: 'bangla_glass_boy' },
  { serial: 82, name: 'মোঃ আশরাফুল', sectionId: 'bangla_glass_boy' },
  { serial: 83, name: 'অভিজিৎ', sectionId: 'bangla_glass_boy' },
  { serial: 84, name: 'মোঃ সিরাম', sectionId: 'bangla_glass_boy' },
  { serial: 85, name: 'মোঃ বকর', sectionId: 'bangla_glass_boy' },
  { serial: 86, name: 'মোঃ নিশান', sectionId: 'bangla_glass_boy' },
  { serial: 87, name: 'মোঃ মহিম', sectionId: 'cleaner' },
  { serial: 88, name: 'মোঃ রবিন', sectionId: 'cleaner' },
  { serial: 89, name: 'আসমা বেগম', sectionId: 'mosla' },
  { serial: 90, name: 'জোসনা বেগম', sectionId: 'mosla' },
  { serial: 91, name: 'মোঃ ফারুক', sectionId: 'security_guard' },
  { serial: 92, name: 'মোঃ নুর', sectionId: 'security_guard' },
  { serial: 93, name: 'মোঃ বাচ্চু', sectionId: 'security_guard' },
  { serial: 94, name: 'মোঃ শরিফ হোসাইন', sectionId: 'supervisor' },
  { serial: 95, name: 'মোঃ সাহিদুর রহমান', sectionId: 'chinese_cashier' },
  { serial: 96, name: 'মোঃ তারেকুল ইসলাম', sectionId: 'chinese_cashier' },
  { serial: 97, name: 'মোঃ আবু বকর সিদ্দিকী', sectionId: 'captain' },
  { serial: 98, name: 'মোঃ মিলাদ', sectionId: 'captain' },
  { serial: 99, name: 'রবিন তাতি', sectionId: 'senior_waiter' },
  { serial: 100, name: 'উসামু মারমা', sectionId: 'senior_waiter' },
  { serial: 101, name: 'মোঃ সাজু', sectionId: 'junior_waiter' },
  { serial: 102, name: 'জীবন মারমা', sectionId: 'junior_waiter' },
  { serial: 103, name: 'মোঃ শাহাদাত', sectionId: 'junior_waiter' },
  { serial: 104, name: 'মোঃ সজিব', sectionId: 'junior_waiter' },
  { serial: 105, name: 'মোঃ ইউসুফ', sectionId: 'italian' },
  { serial: 106, name: 'মোঃ আরিফ', sectionId: 'italian' },
  { serial: 107, name: 'মোঃ সাইফত', sectionId: 'italian' },
  { serial: 108, name: 'মোঃ আমিনির', sectionId: 'chinese' },
  { serial: 109, name: 'মোঃ আবু সাঈদ', sectionId: 'chinese' },
  { serial: 110, name: 'লাবন তাতি', sectionId: 'chinese' },
  { serial: 111, name: 'মোঃ মারুফ', sectionId: 'chinese' },
  { serial: 112, name: 'মোঃ হাসান', sectionId: 'juice_bar' },
  { serial: 113, name: 'মোঃ তানভিদ', sectionId: 'juice_bar' },
  { serial: 114, name: 'মোঃ নিবার', sectionId: 'juice_bar' },
  { serial: 115, name: 'মোঃ জিহাদ', sectionId: 'juice_bar' },
  { serial: 116, name: 'পলাশ তাতি', sectionId: 'house_keeping' },
  { serial: 117, name: 'দীপক তাতি', sectionId: 'house_keeping' },
  { serial: 118, name: 'মোঃ ইসমাইল', sectionId: 'dish_wash' },
  { serial: 119, name: 'মোঃ রিহান', sectionId: 'dish_wash' },
  { serial: 120, name: 'মোঃ শাহিন', sectionId: 'dish_wash' },
  { serial: 121, name: 'মোঃ হৃদয়', sectionId: 'dish_wash' },
];

